export const presetThemes = [
  {
    //   TODO design preset themes that actually look good
    presetName: "Poppin' Blue",
    presetID: 0,
    presetStyles: {
      primaryHue: 'blue',
      primaryLightness: 500,
      secondaryHue: 'blue',
      secondaryLightness: 50,
      primaryFont: 'Poppins',
      primaryFontWeight: 800,
      secondaryFont: 'Poppins',
      secondaryFontWeight: 300,
    },
  },
  {
    presetName: 'Pine Green',
    presetID: 1,
    presetStyles: {
      primaryHue: 'green',
      primaryLightness: 50,
      secondaryHue: 'green',
      secondaryLightness: 600,
      primaryFont: 'Pacifico',
      primaryFontWeight: 900,
      secondaryFont: 'Nunito',
      secondaryFontWeight: 500,
    },
  },
  {
    presetName: 'Cherry Red',
    presetID: 2,
    presetStyles: {
      primaryHue: 'red',
      primaryLightness: 100,
      secondaryHue: 'red',
      secondaryLightness: 500,
      primaryFont: 'Nunito',
      primaryFontWeight: 900,
      secondaryFont: 'Nunito',
      secondaryFontWeight: 100,
    },
  },
  {
    presetName: 'Totally Teal',
    presetID: 3,
    presetStyles: {
      primaryHue: 'teal',
      primaryLightness: 50,
      secondaryHue: 'teal',
      secondaryLightness: 500,
      primaryFont: 'Kufam',
      primaryFontWeight: 800,
      secondaryFont: 'Pacifico',
      secondaryFontWeight: 500,
    },
  },
  {
    presetName: 'Deep Gray',
    presetID: 4,
    presetStyles: {
      primaryHue: 'blue',
      primaryLightness: 100,
      secondaryHue: 'gray',
      secondaryLightness: 900,
      primaryFont: 'ZillaSlab',
      primaryFontWeight: 900,
      secondaryFont: 'Bitter',
      secondaryFontWeight: 200,
    },
  },
  {
    presetName: 'Royal Purple',
    presetID: 5,
    presetStyles: {
      primaryHue: 'yellow',
      primaryLightness: 300,
      secondaryHue: 'purple',
      secondaryLightness: 700,
      primaryFont: 'Redressed',
      primaryFontWeight: 900,
      secondaryFont: 'Literata',
      secondaryFontWeight: 200,
    },
  },
  {
    presetName: 'Classy Pink',
    presetID: 6,
    presetStyles: {
      primaryHue: 'gray',
      primaryLightness: 900,
      secondaryHue: 'pink',
      secondaryLightness: 200,
      primaryFont: 'Trirong',
      primaryFontWeight: 900,
      secondaryFont: 'Kufam',
      secondaryFontWeight: 100,
    },
  },
  {
    presetName: 'Naughtical Yellow',
    presetID: 7,
    presetStyles: {
      primaryHue: 'blue',
      primaryLightness: 800,
      secondaryHue: 'yellow',
      secondaryLightness: 300,
      primaryFont: 'Literata',
      primaryFontWeight: 900,
      secondaryFont: 'Oldenburg',
      secondaryFontWeight: 200,
    },
  },
  {
    presetName: 'Orange Peel',
    presetID: 8,
    presetStyles: {
      primaryHue: 'orange',
      primaryLightness: 400,
      secondaryHue: 'orange',
      secondaryLightness: 50,
      primaryFont: 'Poppins',
      primaryFontWeight: 900,
      secondaryFont: 'Redressed',
      secondaryFontWeight: 500,
    },
  },
  {
    presetName: 'Dreaming Indigo',
    presetID: 9,
    presetStyles: {
      primaryHue: 'blue',
      primaryLightness: 200,
      secondaryHue: 'indigo',
      secondaryLightness: 700,
      primaryFont: 'Bitter',
      primaryFontWeight: 900,
      secondaryFont: 'Nunito',
      secondaryFontWeight: 200,
    },
  },
];
